version: 2
jobs:
  pre:
    working_directory: ~/cci-test
    docker:
      - image: circleci/node:8.1.4
    steps:
      - checkout
      - run: echo "pre job complete"
  post:
    working_directory: ~/cci-test
    docker:
      - image: circleci/node:8.1.4
    steps:
      - checkout
      - run: sudo npm install bower -g
      - run: bower install
      - run: npm install
      - run: sudo npm install gulp -g
      - run: echo "post job complete"
      - persist_to_workspace:
          root: ~/cci-test
          paths:
            - node_modules/
            - bower_components/
  staging:
    docker:
      - image: circleci/node:8.1.4
    filters:
      branches:
        only:
          - /(feature|fix|chore).*/
    steps:
      - checkout
      - attach_workspace:
            at: ~/cci-test
      - run:
          name: Build project
          command: gulp build
      - run: echo "Staging test completed"
  production:
    working_directory: ~/cci-test
    docker:
      - image: circleci/node:8.1.4
    filters:
      branches:
        only:
          - master
    steps:
      - checkout
      # - run:
      #     name: Build project
      #     command: gulp build
      - run: echo "Production test completed"
workflows:
  version: 2
  staging_and_production:
    jobs:
      - pre
      - post:
          requires:
            - pre
      - staging:
          requires:
            - post
      - production:
          requires:
            - post