version: 2
jobs:
  pre:
    working_directory: ~/cci-test
    docker:
      - image: circleci/node:8.1.4
    steps:
      - checkout
      - run: echo "pre job complete"
  post:
    working_directory: ~/cci-test
    docker:
      - image: circleci/node:8.1.4
    steps:
      - checkout
      # - run: sudo npm install bower -g
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: bower install
      - run: npm install
      - run:
          name: Build project
          command: gulp build
      - run: echo "post job complete"
      - persist_to_workspace:
          root: ~/
          paths:
            - cci-test/*
  staging:
    docker:
      - image: circleci/node:8.1.4
    filters:
      branches:
        only:
          - /(feature|fix|chore).*/
    steps:
      - checkout
      # - run:
      #     name: Build project
      #     command: gulp build
      - run: echo "Staging test completed"
  production:
    working_directory: ~/cci-test
    docker:
      - image: circleci/node:8.1.4
    filters:
      branches:
        only:
          - master
    steps:
      - checkout
      # - run:
      #     name: Build project
      #     command: gulp build
      - run: echo "Production test completed"
workflows:
  version: 2
  staging_and_production:
    jobs:
      - pre
      - post:
          requires:
            - pre
      - staging:
          requires:
            - post
      - production:
          requires:
            - post